#pragma once

const char INDEX_HTML[] =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <title>Motor Control</title>\n"
"  <style>\n"
"    :root {\n"
"      --bg-1: #0f172a;\n"
"      --bg-2: #1e293b;\n"
"      --card: #111827cc;\n"
"      --line: #334155;\n"
"      --text: #e5e7eb;\n"
"      --accent: #22c55e;\n"
"      --accent-2: #06b6d4;\n"
"    }\n"
"\n"
"    * { box-sizing: border-box; }\n"
"\n"
"    body {\n"
"      margin: 0;\n"
"      min-height: 100vh;\n"
"      font-family: Verdana, Tahoma, sans-serif;\n"
"      color: var(--text);\n"
"      background:\n"
"        radial-gradient(1200px 500px at 10% -10%, #0ea5e955 0%, transparent 60%),\n"
"        radial-gradient(900px 400px at 100% 0%, #22c55e44 0%, transparent 55%),\n"
"        linear-gradient(160deg, var(--bg-1), var(--bg-2));\n"
"      display: grid;\n"
"      place-items: center;\n"
"      padding: 18px;\n"
"    }\n"
"\n"
"    .panel {\n"
"      width: min(760px, 100%);\n"
"      background: var(--card);\n"
"      border: 1px solid var(--line);\n"
"      border-radius: 18px;\n"
"      padding: 20px;\n"
"      box-shadow: 0 20px 50px #00000055;\n"
"      backdrop-filter: blur(4px);\n"
"      animation: rise 500ms ease-out;\n"
"    }\n"
"\n"
"    h1 {\n"
"      margin: 0 0 8px;\n"
"      font-size: clamp(22px, 3vw, 32px);\n"
"      letter-spacing: 0.4px;\n"
"    }\n"
"\n"
"    p {\n"
"      margin: 0 0 18px;\n"
"      color: #cbd5e1;\n"
"    }\n"
"\n"
"    .status {\n"
"      margin-bottom: 16px;\n"
"      font-size: 14px;\n"
"      padding: 8px 10px;\n"
"      border: 1px dashed #64748b;\n"
"      border-radius: 10px;\n"
"      background: #0b1220aa;\n"
"    }\n"
"\n"
"    .ok { color: #22c55e; }\n"
"    .bad { color: #f87171; }\n"
"\n"
"    .row {\n"
"      display: grid;\n"
"      grid-template-columns: 92px 1fr 54px;\n"
"      gap: 10px;\n"
"      align-items: center;\n"
"      margin: 10px 0;\n"
"      padding: 10px;\n"
"      border-radius: 12px;\n"
"      border: 1px solid #33415566;\n"
"      background: #0f172a99;\n"
"    }\n"
"\n"
"    .name { font-weight: 700; color: #bfdbfe; }\n"
"\n"
"    input[type=\"range\"] {\n"
"      width: 100%;\n"
"      accent-color: var(--accent);\n"
"    }\n"
"\n"
"    .val {\n"
"      text-align: right;\n"
"      font-variant-numeric: tabular-nums;\n"
"      color: var(--accent-2);\n"
"      font-weight: 700;\n"
"    }\n"
"\n"
"    .footer {\n"
"      margin-top: 12px;\n"
"      font-size: 12px;\n"
"      color: #94a3b8;\n"
"    }\n"
"\n"
"    @keyframes rise {\n"
"      from { opacity: 0; transform: translateY(8px) scale(0.99); }\n"
"      to { opacity: 1; transform: translateY(0) scale(1); }\n"
"    }\n"
"\n"
"    @media (max-width: 560px) {\n"
"      .row { grid-template-columns: 1fr; }\n"
"      .val { text-align: left; }\n"
"    }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <main class=\"panel\">\n"
"    <h1>4x Motor Slider Control</h1>\n"
"    <p>Range: 0..250, all start at 0.</p>\n"
"    <div id=\"status\" class=\"status bad\">WS: connecting...</div>\n"
"\n"
"    <div class=\"row\">\n"
"      <div class=\"name\">O1</div>\n"
"      <input id=\"O1\" type=\"range\" min=\"0\" max=\"255\" value=\"0\">\n"
"      <div id=\"v1\" class=\"val\">0</div>\n"
"    </div>\n"
"\n"
"    <div class=\"row\">\n"
"      <div class=\"name\">O2</div>\n"
"      <input id=\"O2\" type=\"range\" min=\"0\" max=\"255\" value=\"0\">\n"
"      <div id=\"v2\" class=\"val\">0</div>\n"
"    </div>\n"
"\n"
"    <div class=\"row\">\n"
"      <div class=\"name\">B1</div>\n"
"      <input id=\"B1\" type=\"range\" min=\"0\" max=\"255\" value=\"0\">\n"
"      <div id=\"v3\" class=\"val\">0</div>\n"
"    </div>\n"
"\n"
"    <div class=\"row\">\n"
"      <div class=\"name\">B2</div>\n"
"      <input id=\"B2\" type=\"range\" min=\"0\" max=\"255\" value=\"0\">\n"
"      <div id=\"v4\" class=\"val\">0</div>\n"
"    </div>\n"
"\n"
"    <div class=\"row\">\n"
"      <div class=\"name\">All Motors</div>\n"
"      <input id=\"mall\" type=\"range\" min=\"0\" max=\"255\" value=\"0\">\n"
"      <div id=\"vall\" class=\"val\">0</div>\n"
"    </div>\n"
"\n"
"    <div class=\"footer\">Payload JSON sent all the time to websocket.</div>\n"
"  </main>\n"
"\n"
"  <script>\n"
"    const sliders = [\n"
"      document.getElementById('O1'),\n"
"      document.getElementById('O2'),\n"
"      document.getElementById('B1'),\n"
"      document.getElementById('B2')\n"
"    ];\n"
"\n"
"    const values = [\n"
"      document.getElementById('v1'),\n"
"      document.getElementById('v2'),\n"
"      document.getElementById('v3'),\n"
"      document.getElementById('v4')\n"
"    ];\n"
"\n"
"    const masterSlider = document.getElementById('mall');\n"
"    const masterValue = document.getElementById('vall');\n"
"\n"
"    const statusEl = document.getElementById('status');\n"
"    let ws = null;\n"
"\n"
"    function updateLabels() {\n"
"      for (let i = 0; i < sliders.length; i++) values[i].textContent = sliders[i].value;\n"
"      masterValue.textContent = masterSlider.value;\n"
"    }\n"
"\n"
"    function payload() {\n"
"      return JSON.stringify({\n"
"        O1: Number(sliders[0].value),\n"
"        O2: Number(sliders[1].value),\n"
"        B1: Number(sliders[2].value),\n"
"        B2: Number(sliders[3].value)\n"
"      });\n"
"    }\n"
"\n"
"    function setStatus(text, ok) {\n"
"      statusEl.textContent = text;\n"
"      statusEl.className = 'status ' + (ok ? 'ok' : 'bad');\n"
"    }\n"
"\n"
"    function connect() {\n"
"      ws = new WebSocket('ws://' + window.location.hostname + ':81/');\n"
"\n"
"      ws.addEventListener('open', () => setStatus('WS: connected', true));\n"
"\n"
"      ws.addEventListener('close', () => {\n"
"        setStatus('WS: disconnected, reconnecting...', false);\n"
"        setTimeout(connect, 1000);\n"
"      });\n"
"\n"
"      ws.addEventListener('error', () => {\n"
"        setStatus('WS: error, reconnecting...', false);\n"
"        try { ws.close(); } catch (e) {}\n"
"      });\n"
"\n"
"      ws.addEventListener('message', (e) => {\n"
"        try {\n"
"          const data = JSON.parse(e.data);\n"
"          if (data.active !== undefined) {\n"
"            document.querySelectorAll('.row').forEach((r, i) => {\n"
"               if (i < 4) r.style.borderColor = (data.active === i) ? '#22c55e' : '#33415566';\n"
"            });\n"
"          }\n"
"        } catch(err) {}\n"
"      });\n"
"    }\n"
"\n"
"    function sendNow() {\n"
"      if (ws && ws.readyState === WebSocket.OPEN) ws.send(payload());\n"
"    }\n"
"\n"
"    sliders.forEach(s => s.addEventListener('input', () => {\n"
"      updateLabels();\n"
"      sendNow();\n"
"    }));\n"
"\n"
"    masterSlider.addEventListener('input', () => {\n"
"      for (let i = 0; i < sliders.length; i++) sliders[i].value = masterSlider.value;\n"
"      updateLabels();\n"
"      sendNow();\n"
"    });\n"
"\n"
"    updateLabels();\n"
"    connect();\n"
"    setInterval(sendNow, 100);\n"
"  </script>\n"
"</body>\n"
"</html>\n";